// Generated by https://quicktype.io

export interface ListVehiculo {
    content:          Vehiculo[];
    pageable:         Pageable;
    last:             boolean;
    totalPages:       number;
    totalElements:    number;
    size:             number;
    number:           number;
    sort:             Sort;
    first:            boolean;
    numberOfElements: number;
    empty:            boolean;
}

export interface Vehiculo {
    id:          string;
    imagen:      string;
    modelo:      string;
    combustion:  string;
    transmision: Transmision;
    disponible:  boolean;
    precioBase:  number;
}

export enum Transmision {
    Automatico = "Automatico",
    Manual = "Manual",
}

export interface Pageable {
    pageNumber: number;
    pageSize:   number;
    sort:       Sort;
    offset:     number;
    unpaged:    boolean;
    paged:      boolean;
}

export interface Sort {
    empty:    boolean;
    sorted:   boolean;
    unsorted: boolean;
}
