// Generated by https://quicktype.io

export interface VehiculoAllDetails {
    id:                 string;
    combustion:         string;
    modelo:             Modelo;
    imagen:             string;
    transmision:        string;
    capacidadPasajeros: number;
    autonomia:          number;
    potencia:           number;
    estado:             string;
    numPuertas:         number;
    disponible:         boolean;
    precioBase:         number;
}

export interface Modelo {
    id: string;
    modelo: string;
    logo:   string;
}
