// Generated by https://quicktype.io

export interface UserDetailsResponse {
    id:       string;
    username: string;
    avatar:   string;
    email:    string;
    telefono: string;
    pin:      string;
}
